In [49]:
%pip install pandas seaborn scikit-learn

Requirement already satisfied: pandas in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: seaborn in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.23.2 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from seaborn) (3.10.7)
Requirement already satisfied: scipy>=1.8.0 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: six>=1.5 in /Users/franciscomorenoq/Documentos/Github/scikit-learn-pro-certification/.conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Loading the adult census dataset

In [50]:
# Loading adult census dataset
import pandas as pd

adult_census = pd.read_csv("datasets/adult-census-numeric.csv")

In [51]:
# Let's take a look at the data
adult_census

,id,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,1,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,2,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,3,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,4,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,5,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,48838,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,48839,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,48840,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,48841,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,48842,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

**The target in this dataset is the 'class' column.**

In [52]:
# Set the target 
target_name = 'class'
target = adult_census[target_name]
target

0        <=50K
1        <=50K
2         >50K
3         >50K
4        <=50K
         ...
48837    <=50K
48838     >50K
48839    <=50K
48840    <=50K
48841     >50K
Name: class, Length: 48842, dtype: object

## Separate the data and the target

In [53]:
# Drop the target column
data = adult_census.drop(columns=[target_name])
data

,id,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,1,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,2,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States
2,3,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
3,4,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States
4,5,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,48838,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States
48838,48839,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States
48839,48840,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States
48840,48841,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States
48841,48842,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States

In [54]:
# Separate the non-numerical features
non_numerical_features = list()
for column in adult_census.columns:
    if adult_census[column].dtype == 'object' and column != target_name:
        non_numerical_features.append(column)

In [55]:
# Drop the non-numerical features
data = data.drop(columns=non_numerical_features)
data

,id,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
0,1,25,226802,7,0,0,40
1,2,38,89814,9,0,0,50
2,3,28,336951,12,0,0,40
3,4,44,160323,10,7688,0,40
4,5,18,103497,10,0,0,30
...,...,...,...,...,...,...,...
48837,48838,27,257302,12,0,0,38
48838,48839,40,154374,9,0,0,40
48839,48840,58,151910,9,0,0,40
48840,48841,22,201490,9,0,0,20
48841,48842,52,287927,9,15024,0,40

In [59]:
# Let's see the data
data.columns

Index(['id', 'age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')

In [60]:
print(
    f"The data contains {data.shape[0]} samples and "
    f"{data.shape[1]} features"
)

The data contains 48842 samples and 7 features

## Fit a model and make predictions

We will use _K-nearest neighbors algorithm_ strategy. To predict the target of a new sample, a k-nearest neighbors takes into account its **k** closest samples in the training set and predicts the mojority of these samples.

In [61]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
_ = model.fit(data, target)

In sckit-learn an object that has ```fit``` method is called an **estimator**. If the estimator additionally has:
- a ```predict_ method```, it is called a **predictor**. Examples of predictores are classifiers or regressors.
- a ```transform``` method, it is called **transformer**. Examples of transformers are scalers or encoders. We will see more about transformers in the next notebook.

The method ```fit``` is composed of two elements: (i) a **learn algorithm** and (ii) some **model states**. The learning algorithm takes the training data and training target as input and sets the model states. These model states are later used to either predict or transform data as explained above.

In [62]:
# Let's use our model to make some predictions using the same dataset
target_predicted = model.predict(data)

In [63]:
# See the firsts 5 predicted targets
target_predicted[:5]

array(['<=50K', '<=50K', '>50K', '<=50K', '<=50K'], dtype=object)

In [64]:
# Let's compare with the true targets
target[:5]

0    <=50K
1    <=50K
2     >50K
3     >50K
4    <=50K
Name: class, dtype: object

In [65]:
# Even we can check if the predictions are correct
target_predicted[:5] == target[:5]

0     True
1     True
2     True
3    False
4     True
Name: class, dtype: bool

In [69]:
print(
    "Number of correct prediction: "
    f"{(target[:5] == target_predicted[:5]).sum()} / 5"
)

Number of correct prediction: 4 / 5

In [70]:
# We can also calculate the average of the sucess rate
(target == target_predicted).mean()

np.float64(0.8202366815445723)

## Train-test data split

### Because the original dataset is not available, we'll split the current one

In [72]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(
    data,
    target,
    test_size=0.2,
    random_state=37
)

In [73]:
_ = model.fit(data_train, target_train)

In [74]:
# Let's calculate the accuracy of our model
accuracy = model.score(data_test, target_test)
model_name = model.__class__.__name__

print(f"The test accuracy of {model_name} is {accuracy:.3f}")

The test accuracy of KNeighborsClassifier is 0.767